variable "owner" {
  default = env("OWNER")
}

variable "name" {
  default = "phantom-stranger"
}

data "amazon-ami" "autogenerated_1" {
  filters = {
    name                = "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200625"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = "eu-west-2"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  ami_name      = format("%s-k3s-server-${local.timestamp}", var.name)
  instance_type = "t3.large"
  region        = "eu-west-2"
  run_tags = {
    owner = var.owner
    type  = "k3s-server"
  }
  run_volume_tags = {
    owner = var.owner
    type  = "k3s-server"
  }
  source_ami   = data.amazon-ami.autogenerated_1.id
  ssh_username = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "file" {
    destination = "/home/ubuntu/"
    source      = "./provision.sh"
  }

  provisioner "shell" {
    script = "./provision.sh"
  }
}
